url: https://www.roots2harvestfoundation.org
baseurl: ""

# Site settings
title: Roots2Harvest Foundation
email: info@roots2harvestfoundation.org
description: "Roots2Harvest Foundation reconnects Birmingham communities to the land through agricultural education and community-based participatory research, building food sovereignty and health sovereignty from the ground up."

# Team names, titles and social links
people:
- name: Dr. Amanda D. Clark
  pic: 1
  position: Founder & Executive Director
  social:
    - title: linkedin
      url: "https://www.linkedin.com/in/adcbio/"
    - title: instagram
      url: "https://www.instagram.com/dramandacphd/"

- name: Grace Wettstone
  pic: 2
  position: Community Engagement & Wellness Officer
  social:
    - title: linkedin
      url: "#"
    - title: instagram
      url: "#"

- name: Quinton Harvill
  pic: 3
  position: Innovation & Operations Development Officer
  social:
    - title: linkedin
      url: "https://www.linkedin.com/in/quintonharvill?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app"
    - title: instagram
      url: "https://www.instagram.com/q.dmarco?igsh=MTRmcjI0eWludWp4Mw%3D%3D&utm_source=qr"

# Social networks
social:
  - title: instagram
    url: "https://www.instagram.com/roots2harvest_foundation/"
  - title: facebook
    url: "#"

# Postal address
address:
  - line: 1450 Forestdale Blvd
  - line: Unit 310036
  - line: Birmingham, AL 35214

# Build settings
markdown: kramdown
permalink: pretty
