url: https://www.roots2harvestfoundation.org
baseurl: /agency-jekyll-theme/

# Site settings
title: Roots2Harvest Foundation
email: info@roots2harvestfoundation.org
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Amanda Clark
  pic: 1
  position: Executive Director
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: #

- name: Grace Wettstone
  pic: 2
  position: Community Engagement & Wellness Officer
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: #

- name: Quinton Harvill
  pic: 3
  position: Innovation and Operations Development Officer
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 1450 Forestdale Blvd
  - line: Unit 310036
  - line: Birmingham, AL 35214

# Build settings
markdown: kramdown
permalink: pretty
